version: '2.1'

services:
    rabbitmq:
        image: rabbitmq:latest
        container_name: poc-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - pocnetwork
    
    gitblit:
        build: ./gitblit-image
        container_name: poc-gitblit
        image: springpoc/gitblit
        ports:
            - "8090:8090"
            - "8453:8453"
            - "9418:9418"
            - "29418:29418"
        networks:
            - pocnetwork

    configservice1:
        build: ./configuration-service
        container_name: poc-configserver1
        image: springpoc/configserver1
        ports:
            - "8888:8888"
        depends_on:
          - rabbitmq
          - gitblit
        networks:
          - pocnetwork
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8888/healthcheck || exit 1"]
            #test: curl -f https://localhost:8888 || exit 1
            #test: ["CMD", "curl", "-f", "http://localhost:8888"]
            interval: 20s
            timeout: 10s
            retries: 5

          
    configclient1:
        build: 
            context: ./configuration-client
        environment:
           - SPRING_PROFILES_ACTIVE=default
           - SPRING_CLOUD_CONFIG_URI=http://configservice1:8889
        container_name: poc-configclient1
        image: springpoc/configclient1
        ports:
            - "8080:8080"
        depends_on:
            configservice1:
                condition: service_healthy
            rabbitmq:
                condition: service_started
        networks:
          - pocnetwork

networks:
  pocnetwork:
    driver: bridge
  